// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef _EUROTRUCK_STEERING_WHEEL_UI_H
#define _EUROTRUCK_STEERING_WHEEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_ScreenDriving.h"
#include "ui_ScreenControls.h"
#include "ui_ScreenTruck.h"
#include "ui_ScreenJob.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_headlights_png);    // assets/headlights.png
LV_IMG_DECLARE(ui_img_headlights_beam_png);    // assets/headlights_beam.png
LV_IMG_DECLARE(ui_img_wipers_png);    // assets/wipers.png
LV_IMG_DECLARE(ui_img_alert_triangle_png);    // assets/alert_triangle.png

// FONTS
LV_FONT_DECLARE(ui_font_FontDataMedium);
LV_FONT_DECLARE(ui_font_FontSpeedHuge);
LV_FONT_DECLARE(ui_font_FontUILarge);
LV_FONT_DECLARE(ui_font_FontUIRegular);
LV_FONT_DECLARE(ui_font_FontUISmall);
LV_FONT_DECLARE(ui_font_FontUITiny);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
