// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void uiEventLights(lv_event_t * e);
void uiEventHighBeam(lv_event_t * e);
void uiEventGearR(lv_event_t * e);
void uiEventGearN(lv_event_t * e);
void uiEventGearD(lv_event_t * e);
void uiEventWipers(lv_event_t * e);
void uiEventHazards(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
