// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef UI_SCREENJOB_H
#define UI_SCREENJOB_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenJob
extern void ui_ScreenJob_screen_init(void);
extern void ui_ScreenJob_screen_destroy(void);
extern lv_obj_t * ui_ScreenJob;
extern lv_obj_t * ui_JobContainer;
extern lv_obj_t * ui_CardCargo;
extern lv_obj_t * ui_cargoTitle;
extern lv_obj_t * ui_cargoValue;
extern lv_obj_t * ui_CardDest;
extern lv_obj_t * ui_destTitle;
extern lv_obj_t * ui_destValue;
extern lv_obj_t * ui_CardReward;
extern lv_obj_t * ui_rewardTitle;
extern lv_obj_t * ui_rewardValue;
extern lv_obj_t * ui_CardDamage;
extern lv_obj_t * ui_damageTitle;
extern lv_obj_t * ui_damageValue;
extern lv_obj_t * ui_TabBarPanel3;
extern void ui_event_BtnNavDriving3(lv_event_t * e);
extern lv_obj_t * ui_BtnNavDriving3;
extern lv_obj_t * ui_LblNavDriving3;
extern void ui_event_BtnNavCtrl3(lv_event_t * e);
extern lv_obj_t * ui_BtnNavCtrl3;
extern lv_obj_t * ui_LblNavCtrl3;
extern void ui_event_BtnNavTruck3(lv_event_t * e);
extern lv_obj_t * ui_BtnNavTruck3;
extern lv_obj_t * ui_LblNavTruck3;
extern lv_obj_t * ui_BtnNavJob3;
extern lv_obj_t * ui_LblNavJob3;
extern lv_obj_t * ui_HeaderPanel3;
extern lv_obj_t * ui_StatusLabel3;
extern lv_obj_t * ui_TitleLabel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

