// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#include "ui.h"

lv_obj_t * ui_ScreenControls = NULL;
lv_obj_t * ui_HeaderPanel1 = NULL;
lv_obj_t * ui_TitleLabel1 = NULL;
lv_obj_t * ui_StatusLabel1 = NULL;
lv_obj_t * ui_TabBarPanel1 = NULL;
lv_obj_t * ui_BtnNavDriving1 = NULL;
lv_obj_t * ui_LblNavDriving1 = NULL;
lv_obj_t * ui_BtnNavCtrl = NULL;
lv_obj_t * ui_LblNavCtrl = NULL;
lv_obj_t * ui_BtnNavTruck1 = NULL;
lv_obj_t * ui_LblNavTruck1 = NULL;
lv_obj_t * ui_BtnNavJob1 = NULL;
lv_obj_t * ui_LblNavJob1 = NULL;
lv_obj_t * ui_ControlsContainer = NULL;
lv_obj_t * ui_LightsPanel = NULL;
lv_obj_t * ui_BtnLights = NULL;
lv_obj_t * ui_ImgLights = NULL;
lv_obj_t * ui_LblLigths = NULL;
lv_obj_t * ui_BtnHighBeam = NULL;
lv_obj_t * ui_ImgBeam = NULL;
lv_obj_t * ui_LblBeam = NULL;
lv_obj_t * ui_GearSelector = NULL;
lv_obj_t * ui_LabelR = NULL;
lv_obj_t * ui_LabelN = NULL;
lv_obj_t * ui_LabelD = NULL;
lv_obj_t * ui_UtilityPanel = NULL;
lv_obj_t * ui_BtnWipers = NULL;
lv_obj_t * ui_ImgWipers = NULL;
lv_obj_t * ui_LblWipers = NULL;
lv_obj_t * ui_BtnHazards = NULL;
lv_obj_t * ui_ImgHazards = NULL;
lv_obj_t * ui_LblHazards = NULL;
// event funtions
void ui_event_BtnNavDriving1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenDriving, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDriving_screen_init);
    }
}

void ui_event_BtnNavTruck1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTruck, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTruck_screen_init);
    }
}

void ui_event_BtnNavJob1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenJob, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenJob_screen_init);
    }
}

void ui_event_BtnLights(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventLights(e);
    }
}

void ui_event_BtnHighBeam(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventHighBeam(e);
    }
}

void ui_event_LabelR(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventGearR(e);
    }
}

void ui_event_LabelN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventGearN(e);
    }
}

void ui_event_LabelD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventGearD(e);
    }
}

void ui_event_BtnWipers(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventWipers(e);
    }
}

void ui_event_BtnHazards(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        uiEventHazards(e);
    }
}

// build funtions

void ui_ScreenControls_screen_init(void)
{
    ui_ScreenControls = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenControls, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderPanel1 = lv_obj_create(ui_ScreenControls);
    lv_obj_set_width(ui_HeaderPanel1, 800);
    lv_obj_set_height(ui_HeaderPanel1, 60);
    lv_obj_set_align(ui_HeaderPanel1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HeaderPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaderPanel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaderPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel1 = lv_label_create(ui_HeaderPanel1);
    lv_obj_set_width(ui_TitleLabel1, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_TitleLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel1, 30);
    lv_obj_set_y(ui_TitleLabel1, 0);
    lv_obj_set_align(ui_TitleLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TitleLabel1, "TRUCK-ESP32-CLUSTER v1.0\n");
    lv_obj_set_style_text_color(ui_TitleLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitleLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLabel1, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel1 = lv_label_create(ui_HeaderPanel1);
    lv_obj_set_width(ui_StatusLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel1, -30);
    lv_obj_set_y(ui_StatusLabel1, 0);
    lv_obj_set_align(ui_StatusLabel1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_StatusLabel1, "RTOS LINK ACTIVE");
    lv_obj_set_style_text_color(ui_StatusLabel1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel1, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabBarPanel1 = lv_obj_create(ui_ScreenControls);
    lv_obj_set_width(ui_TabBarPanel1, 800);
    lv_obj_set_height(ui_TabBarPanel1, 75);
    lv_obj_set_align(ui_TabBarPanel1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabBarPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabBarPanel1, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabBarPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabBarPanel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabBarPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabBarPanel1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavDriving1 = lv_btn_create(ui_TabBarPanel1);
    lv_obj_set_width(ui_BtnNavDriving1, 200);
    lv_obj_set_height(ui_BtnNavDriving1, 75);
    lv_obj_set_align(ui_BtnNavDriving1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavDriving1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavDriving1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavDriving1, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavDriving1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavDriving1 = lv_label_create(ui_BtnNavDriving1);
    lv_obj_set_width(ui_LblNavDriving1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavDriving1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavDriving1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavDriving1, "DRIVING");
    lv_obj_set_style_text_color(ui_LblNavDriving1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavDriving1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavDriving1, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavCtrl = lv_btn_create(ui_TabBarPanel1);
    lv_obj_set_width(ui_BtnNavCtrl, 200);
    lv_obj_set_height(ui_BtnNavCtrl, 75);
    lv_obj_set_x(ui_BtnNavCtrl, 200);
    lv_obj_set_y(ui_BtnNavCtrl, 0);
    lv_obj_set_align(ui_BtnNavCtrl, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavCtrl, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavCtrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavCtrl, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavCtrl = lv_label_create(ui_BtnNavCtrl);
    lv_obj_set_width(ui_LblNavCtrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavCtrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavCtrl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavCtrl, "CTRL");
    lv_obj_set_style_text_color(ui_LblNavCtrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavCtrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavCtrl, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavTruck1 = lv_btn_create(ui_TabBarPanel1);
    lv_obj_set_width(ui_BtnNavTruck1, 200);
    lv_obj_set_height(ui_BtnNavTruck1, 75);
    lv_obj_set_x(ui_BtnNavTruck1, 400);
    lv_obj_set_y(ui_BtnNavTruck1, 0);
    lv_obj_set_align(ui_BtnNavTruck1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavTruck1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavTruck1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavTruck1, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavTruck1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavTruck1 = lv_label_create(ui_BtnNavTruck1);
    lv_obj_set_width(ui_LblNavTruck1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavTruck1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavTruck1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavTruck1, "TRUCK");
    lv_obj_set_style_text_color(ui_LblNavTruck1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavTruck1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavTruck1, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavJob1 = lv_btn_create(ui_TabBarPanel1);
    lv_obj_set_width(ui_BtnNavJob1, 200);
    lv_obj_set_height(ui_BtnNavJob1, 75);
    lv_obj_set_x(ui_BtnNavJob1, 600);
    lv_obj_set_y(ui_BtnNavJob1, 0);
    lv_obj_set_align(ui_BtnNavJob1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavJob1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavJob1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavJob1, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavJob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavJob1 = lv_label_create(ui_BtnNavJob1);
    lv_obj_set_width(ui_LblNavJob1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavJob1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavJob1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavJob1, "JOB");
    lv_obj_set_style_text_color(ui_LblNavJob1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavJob1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavJob1, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlsContainer = lv_obj_create(ui_ScreenControls);
    lv_obj_set_width(ui_ControlsContainer, 800);
    lv_obj_set_height(ui_ControlsContainer, 345);
    lv_obj_set_x(ui_ControlsContainer, 0);
    lv_obj_set_y(ui_ControlsContainer, 60);
    lv_obj_set_align(ui_ControlsContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_ControlsContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ControlsContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ControlsContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ControlsContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ControlsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_row(ui_ControlsContainer, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ControlsContainer, 40, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LightsPanel = lv_obj_create(ui_ControlsContainer);
    lv_obj_set_width(ui_LightsPanel, 180);
    lv_obj_set_height(ui_LightsPanel, 320);
    lv_obj_set_align(ui_LightsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LightsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LightsPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_LightsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnLights = lv_btn_create(ui_LightsPanel);
    lv_obj_set_width(ui_BtnLights, 180);
    lv_obj_set_height(ui_BtnLights, 140);
    lv_obj_set_align(ui_BtnLights, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BtnLights, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BtnLights, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnLights, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnLights, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnLights, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnLights, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnLights, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnLights, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnLights, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnLights, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BtnLights, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BtnLights, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgLights = lv_img_create(ui_BtnLights);
    lv_img_set_src(ui_ImgLights, &ui_img_headlights_png);
    lv_obj_set_width(ui_ImgLights, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgLights, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgLights, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgLights, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgLights, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgLights, 255);
    lv_obj_set_style_img_recolor(ui_ImgLights, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgLights, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblLigths = lv_label_create(ui_BtnLights);
    lv_obj_set_width(ui_LblLigths, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblLigths, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblLigths, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblLigths, "Luces");
    lv_obj_set_style_text_color(ui_LblLigths, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblLigths, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblLigths, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnHighBeam = lv_btn_create(ui_LightsPanel);
    lv_obj_set_width(ui_BtnHighBeam, 180);
    lv_obj_set_height(ui_BtnHighBeam, 140);
    lv_obj_set_align(ui_BtnHighBeam, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BtnHighBeam, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BtnHighBeam, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHighBeam, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHighBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnHighBeam, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnHighBeam, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHighBeam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnHighBeam, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnHighBeam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnHighBeam, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgBeam = lv_img_create(ui_BtnHighBeam);
    lv_img_set_src(ui_ImgBeam, &ui_img_headlights_beam_png);
    lv_obj_set_width(ui_ImgBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgBeam, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgBeam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgBeam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgBeam, 255);
    lv_obj_set_style_img_recolor(ui_ImgBeam, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgBeam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblBeam = lv_label_create(ui_BtnHighBeam);
    lv_obj_set_width(ui_LblBeam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblBeam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblBeam, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblBeam, "Altas");
    lv_obj_set_style_text_color(ui_LblBeam, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblBeam, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblBeam, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearSelector = lv_obj_create(ui_ControlsContainer);
    lv_obj_set_width(ui_GearSelector, 260);
    lv_obj_set_height(ui_GearSelector, 320);
    lv_obj_set_align(ui_GearSelector, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GearSelector, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GearSelector, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearSelector, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GearSelector, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GearSelector, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearSelector, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_GearSelector, lv_color_hex(0x0096FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearSelector, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GearSelector, 3, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_GearSelector, lv_color_hex(0x0096FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_GearSelector, 30, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelR = lv_label_create(ui_GearSelector);
    lv_obj_set_width(ui_LabelR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelR, "R");
    lv_obj_set_style_text_color(ui_LabelR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelR, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelR, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelN = lv_label_create(ui_GearSelector);
    lv_obj_set_width(ui_LabelN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelN, "N");
    lv_obj_set_style_text_color(ui_LabelN, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelN, &ui_font_FontSpeedHuge, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelN, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelD = lv_label_create(ui_GearSelector);
    lv_obj_set_width(ui_LabelD, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelD, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelD, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelD, "D");
    lv_obj_set_style_text_color(ui_LabelD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelD, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelD, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UtilityPanel = lv_obj_create(ui_ControlsContainer);
    lv_obj_set_width(ui_UtilityPanel, 180);
    lv_obj_set_height(ui_UtilityPanel, 320);
    lv_obj_set_align(ui_UtilityPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_UtilityPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_UtilityPanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_UtilityPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UtilityPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UtilityPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnWipers = lv_btn_create(ui_UtilityPanel);
    lv_obj_set_width(ui_BtnWipers, 180);
    lv_obj_set_height(ui_BtnWipers, 140);
    lv_obj_set_align(ui_BtnWipers, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BtnWipers, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BtnWipers, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnWipers, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnWipers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnWipers, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnWipers, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnWipers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnWipers, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnWipers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnWipers, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgWipers = lv_img_create(ui_BtnWipers);
    lv_img_set_src(ui_ImgWipers, &ui_img_wipers_png);
    lv_obj_set_width(ui_ImgWipers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgWipers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgWipers, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgWipers, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgWipers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgWipers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgWipers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblWipers = lv_label_create(ui_BtnWipers);
    lv_obj_set_width(ui_LblWipers, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblWipers, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblWipers, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblWipers, "Limpiaparabrisas");
    lv_obj_set_style_text_color(ui_LblWipers, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblWipers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblWipers, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnHazards = lv_btn_create(ui_UtilityPanel);
    lv_obj_set_width(ui_BtnHazards, 180);
    lv_obj_set_height(ui_BtnHazards, 140);
    lv_obj_set_align(ui_BtnHazards, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BtnHazards, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BtnHazards, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnHazards, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnHazards, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnHazards, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnHazards, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnHazards, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BtnHazards, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BtnHazards, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnHazards, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgHazards = lv_img_create(ui_BtnHazards);
    lv_img_set_src(ui_ImgHazards, &ui_img_alert_triangle_png);
    lv_obj_set_width(ui_ImgHazards, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImgHazards, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImgHazards, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgHazards, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgHazards, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImgHazards, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImgHazards, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblHazards = lv_label_create(ui_BtnHazards);
    lv_obj_set_width(ui_LblHazards, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblHazards, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblHazards, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblHazards, "Intermitentes");
    lv_obj_set_style_text_color(ui_LblHazards, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblHazards, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblHazards, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnNavDriving1, ui_event_BtnNavDriving1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavTruck1, ui_event_BtnNavTruck1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavJob1, ui_event_BtnNavJob1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnLights, ui_event_BtnLights, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnHighBeam, ui_event_BtnHighBeam, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelR, ui_event_LabelR, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelN, ui_event_LabelN, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LabelD, ui_event_LabelD, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnWipers, ui_event_BtnWipers, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnHazards, ui_event_BtnHazards, LV_EVENT_ALL, NULL);

}

void ui_ScreenControls_screen_destroy(void)
{
    if(ui_ScreenControls) lv_obj_del(ui_ScreenControls);

    // NULL screen variables
    ui_ScreenControls = NULL;
    ui_HeaderPanel1 = NULL;
    ui_TitleLabel1 = NULL;
    ui_StatusLabel1 = NULL;
    ui_TabBarPanel1 = NULL;
    ui_BtnNavDriving1 = NULL;
    ui_LblNavDriving1 = NULL;
    ui_BtnNavCtrl = NULL;
    ui_LblNavCtrl = NULL;
    ui_BtnNavTruck1 = NULL;
    ui_LblNavTruck1 = NULL;
    ui_BtnNavJob1 = NULL;
    ui_LblNavJob1 = NULL;
    ui_ControlsContainer = NULL;
    ui_LightsPanel = NULL;
    ui_BtnLights = NULL;
    ui_ImgLights = NULL;
    ui_LblLigths = NULL;
    ui_BtnHighBeam = NULL;
    ui_ImgBeam = NULL;
    ui_LblBeam = NULL;
    ui_GearSelector = NULL;
    ui_LabelR = NULL;
    ui_LabelN = NULL;
    ui_LabelD = NULL;
    ui_UtilityPanel = NULL;
    ui_BtnWipers = NULL;
    ui_ImgWipers = NULL;
    ui_LblWipers = NULL;
    ui_BtnHazards = NULL;
    ui_ImgHazards = NULL;
    ui_LblHazards = NULL;

}
