// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef UI_SCREENTRUCK_H
#define UI_SCREENTRUCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenTruck
extern void ui_ScreenTruck_screen_init(void);
extern void ui_ScreenTruck_screen_destroy(void);
extern lv_obj_t * ui_ScreenTruck;
extern lv_obj_t * ui_HeaderPanel2;
extern lv_obj_t * ui_TitleLabel2;
extern lv_obj_t * ui_StatusLabel2;
extern lv_obj_t * ui_TabBarPanel2;
extern void ui_event_BtnNavDriving2(lv_event_t * e);
extern lv_obj_t * ui_BtnNavDriving2;
extern lv_obj_t * ui_LblNavDriving2;
extern void ui_event_BtnNavCtrl2(lv_event_t * e);
extern lv_obj_t * ui_BtnNavCtrl2;
extern lv_obj_t * ui_LblNavCtrl2;
extern lv_obj_t * ui_BtnNavTruck2;
extern lv_obj_t * ui_LblNavTruck2;
extern void ui_event_BtnNavJob2(lv_event_t * e);
extern lv_obj_t * ui_BtnNavJob2;
extern lv_obj_t * ui_LblNavJob2;
extern lv_obj_t * ui_TruckVisual;
extern lv_obj_t * ui_CabinBody;
extern lv_obj_t * ui_ChassisBody;
extern lv_obj_t * ui_EngineBlock;
extern lv_obj_t * ui_TransBlock;
extern lv_obj_t * ui_TrailerBody;
extern lv_obj_t * ui_WheelFL;
extern lv_obj_t * ui_WheelFR;
extern lv_obj_t * ui_WheelML;
extern lv_obj_t * ui_WheelMR;
extern lv_obj_t * ui_WheelRL;
extern lv_obj_t * ui_WheelRR;
extern lv_obj_t * ui_MotorValue;
extern lv_obj_t * ui_TransTitle;
extern lv_obj_t * ui_TransValue;
extern lv_obj_t * ui_MotorTitle;
extern lv_obj_t * ui_CabinTitle;
extern lv_obj_t * ui_CabinValue;
extern lv_obj_t * ui_ChassisTitle;
extern lv_obj_t * ui_ChassisValue;
extern lv_obj_t * ui_TrailerTitle;
extern lv_obj_t * ui_TrailerValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

