// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#include "ui.h"

lv_obj_t * ui_ScreenJob = NULL;
lv_obj_t * ui_JobContainer = NULL;
lv_obj_t * ui_CardCargo = NULL;
lv_obj_t * ui_cargoTitle = NULL;
lv_obj_t * ui_cargoValue = NULL;
lv_obj_t * ui_CardDest = NULL;
lv_obj_t * ui_destTitle = NULL;
lv_obj_t * ui_destValue = NULL;
lv_obj_t * ui_CardReward = NULL;
lv_obj_t * ui_rewardTitle = NULL;
lv_obj_t * ui_rewardValue = NULL;
lv_obj_t * ui_CardDamage = NULL;
lv_obj_t * ui_damageTitle = NULL;
lv_obj_t * ui_damageValue = NULL;
lv_obj_t * ui_TabBarPanel3 = NULL;
lv_obj_t * ui_BtnNavDriving3 = NULL;
lv_obj_t * ui_LblNavDriving3 = NULL;
lv_obj_t * ui_BtnNavCtrl3 = NULL;
lv_obj_t * ui_LblNavCtrl3 = NULL;
lv_obj_t * ui_BtnNavTruck3 = NULL;
lv_obj_t * ui_LblNavTruck3 = NULL;
lv_obj_t * ui_BtnNavJob3 = NULL;
lv_obj_t * ui_LblNavJob3 = NULL;
lv_obj_t * ui_HeaderPanel3 = NULL;
lv_obj_t * ui_StatusLabel3 = NULL;
lv_obj_t * ui_TitleLabel4 = NULL;
// event funtions
void ui_event_BtnNavDriving3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenDriving, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDriving_screen_init);
    }
}

void ui_event_BtnNavCtrl3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenControls, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenControls_screen_init);
    }
}

void ui_event_BtnNavTruck3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTruck, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTruck_screen_init);
    }
}

// build funtions

void ui_ScreenJob_screen_init(void)
{
    ui_ScreenJob = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenJob, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenJob, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenJob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JobContainer = lv_obj_create(ui_ScreenJob);
    lv_obj_set_width(ui_JobContainer, 750);
    lv_obj_set_height(ui_JobContainer, 340);
    lv_obj_set_x(ui_JobContainer, 0);
    lv_obj_set_y(ui_JobContainer, -10);
    lv_obj_set_align(ui_JobContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_JobContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_JobContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_JobContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_JobContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_JobContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_JobContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_JobContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardCargo = lv_obj_create(ui_JobContainer);
    lv_obj_set_width(ui_CardCargo, 700);
    lv_obj_set_height(ui_CardCargo, 75);
    lv_obj_set_align(ui_CardCargo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CardCargo, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CardCargo, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CardCargo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardCargo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardCargo, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardCargo, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CardCargo, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CardCargo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CardCargo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CardCargo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CardCargo, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CardCargo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cargoTitle = lv_label_create(ui_CardCargo);
    lv_obj_set_width(ui_cargoTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cargoTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cargoTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cargoTitle, "Cargo");
    lv_obj_set_style_text_color(ui_cargoTitle, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cargoTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cargoTitle, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cargoValue = lv_label_create(ui_CardCargo);
    lv_obj_set_width(ui_cargoValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cargoValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_cargoValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_cargoValue, "Medical Vaccines");
    lv_obj_set_style_text_color(ui_cargoValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cargoValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cargoValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDest = lv_obj_create(ui_JobContainer);
    lv_obj_set_width(ui_CardDest, 700);
    lv_obj_set_height(ui_CardDest, 75);
    lv_obj_set_align(ui_CardDest, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CardDest, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CardDest, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CardDest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardDest, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardDest, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDest, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CardDest, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CardDest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CardDest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CardDest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CardDest, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CardDest, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_destTitle = lv_label_create(ui_CardDest);
    lv_obj_set_width(ui_destTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_destTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_destTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_destTitle, "Destination");
    lv_obj_set_style_text_color(ui_destTitle, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_destTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_destTitle, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_destValue = lv_label_create(ui_CardDest);
    lv_obj_set_width(ui_destValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_destValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_destValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_destValue, "Belgium");
    lv_obj_set_style_text_color(ui_destValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_destValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_destValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardReward = lv_obj_create(ui_JobContainer);
    lv_obj_set_width(ui_CardReward, 700);
    lv_obj_set_height(ui_CardReward, 75);
    lv_obj_set_align(ui_CardReward, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CardReward, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CardReward, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CardReward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardReward, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardReward, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardReward, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CardReward, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CardReward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CardReward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CardReward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CardReward, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CardReward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rewardTitle = lv_label_create(ui_CardReward);
    lv_obj_set_width(ui_rewardTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rewardTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rewardTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rewardTitle, "Reward");
    lv_obj_set_style_text_color(ui_rewardTitle, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rewardTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rewardTitle, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rewardValue = lv_label_create(ui_CardReward);
    lv_obj_set_width(ui_rewardValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rewardValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rewardValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rewardValue, "$10,000");
    lv_obj_set_style_text_color(ui_rewardValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rewardValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rewardValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CardDamage = lv_obj_create(ui_JobContainer);
    lv_obj_set_width(ui_CardDamage, 700);
    lv_obj_set_height(ui_CardDamage, 75);
    lv_obj_set_align(ui_CardDamage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CardDamage, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CardDamage, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CardDamage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CardDamage, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CardDamage, lv_color_hex(0x12141A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CardDamage, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CardDamage, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CardDamage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CardDamage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CardDamage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CardDamage, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CardDamage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_damageTitle = lv_label_create(ui_CardDamage);
    lv_obj_set_width(ui_damageTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_damageTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_damageTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_damageTitle, "Damage");
    lv_obj_set_style_text_color(ui_damageTitle, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_damageTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_damageTitle, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_damageValue = lv_label_create(ui_CardDamage);
    lv_obj_set_width(ui_damageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_damageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_damageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_damageValue, "Medical Vaccines");
    lv_obj_set_style_text_color(ui_damageValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_damageValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_damageValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabBarPanel3 = lv_obj_create(ui_ScreenJob);
    lv_obj_set_width(ui_TabBarPanel3, 800);
    lv_obj_set_height(ui_TabBarPanel3, 75);
    lv_obj_set_align(ui_TabBarPanel3, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabBarPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabBarPanel3, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabBarPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabBarPanel3, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabBarPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabBarPanel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavDriving3 = lv_btn_create(ui_TabBarPanel3);
    lv_obj_set_width(ui_BtnNavDriving3, 200);
    lv_obj_set_height(ui_BtnNavDriving3, 75);
    lv_obj_set_align(ui_BtnNavDriving3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavDriving3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavDriving3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavDriving3, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavDriving3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavDriving3 = lv_label_create(ui_BtnNavDriving3);
    lv_obj_set_width(ui_LblNavDriving3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavDriving3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavDriving3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavDriving3, "DRIVING");
    lv_obj_set_style_text_color(ui_LblNavDriving3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavDriving3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavDriving3, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavCtrl3 = lv_btn_create(ui_TabBarPanel3);
    lv_obj_set_width(ui_BtnNavCtrl3, 200);
    lv_obj_set_height(ui_BtnNavCtrl3, 75);
    lv_obj_set_x(ui_BtnNavCtrl3, 200);
    lv_obj_set_y(ui_BtnNavCtrl3, 0);
    lv_obj_set_align(ui_BtnNavCtrl3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavCtrl3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavCtrl3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavCtrl3, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavCtrl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavCtrl3 = lv_label_create(ui_BtnNavCtrl3);
    lv_obj_set_width(ui_LblNavCtrl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavCtrl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavCtrl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavCtrl3, "CTRL");
    lv_obj_set_style_text_color(ui_LblNavCtrl3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavCtrl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavCtrl3, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavTruck3 = lv_btn_create(ui_TabBarPanel3);
    lv_obj_set_width(ui_BtnNavTruck3, 200);
    lv_obj_set_height(ui_BtnNavTruck3, 75);
    lv_obj_set_x(ui_BtnNavTruck3, 400);
    lv_obj_set_y(ui_BtnNavTruck3, 0);
    lv_obj_set_align(ui_BtnNavTruck3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavTruck3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavTruck3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavTruck3, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavTruck3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavTruck3 = lv_label_create(ui_BtnNavTruck3);
    lv_obj_set_width(ui_LblNavTruck3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavTruck3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavTruck3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavTruck3, "TRUCK");
    lv_obj_set_style_text_color(ui_LblNavTruck3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavTruck3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavTruck3, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavJob3 = lv_btn_create(ui_TabBarPanel3);
    lv_obj_set_width(ui_BtnNavJob3, 200);
    lv_obj_set_height(ui_BtnNavJob3, 75);
    lv_obj_set_x(ui_BtnNavJob3, 600);
    lv_obj_set_y(ui_BtnNavJob3, 0);
    lv_obj_set_align(ui_BtnNavJob3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavJob3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavJob3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavJob3, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavJob3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavJob3 = lv_label_create(ui_BtnNavJob3);
    lv_obj_set_width(ui_LblNavJob3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavJob3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavJob3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavJob3, "JOB");
    lv_obj_set_style_text_color(ui_LblNavJob3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavJob3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavJob3, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderPanel3 = lv_obj_create(ui_ScreenJob);
    lv_obj_set_width(ui_HeaderPanel3, 800);
    lv_obj_set_height(ui_HeaderPanel3, 60);
    lv_obj_set_align(ui_HeaderPanel3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HeaderPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaderPanel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaderPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel3 = lv_label_create(ui_HeaderPanel3);
    lv_obj_set_width(ui_StatusLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel3, -30);
    lv_obj_set_y(ui_StatusLabel3, 0);
    lv_obj_set_align(ui_StatusLabel3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_StatusLabel3, "RTOS LINK ACTIVE");
    lv_obj_set_style_text_color(ui_StatusLabel3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel3, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel4 = lv_label_create(ui_HeaderPanel3);
    lv_obj_set_width(ui_TitleLabel4, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_TitleLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel4, 30);
    lv_obj_set_y(ui_TitleLabel4, 0);
    lv_obj_set_align(ui_TitleLabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TitleLabel4, "TRUCK-ESP32-CLUSTER v1.0\n");
    lv_obj_set_style_text_color(ui_TitleLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitleLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLabel4, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnNavDriving3, ui_event_BtnNavDriving3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavCtrl3, ui_event_BtnNavCtrl3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavTruck3, ui_event_BtnNavTruck3, LV_EVENT_ALL, NULL);

}

void ui_ScreenJob_screen_destroy(void)
{
    if(ui_ScreenJob) lv_obj_del(ui_ScreenJob);

    // NULL screen variables
    ui_ScreenJob = NULL;
    ui_JobContainer = NULL;
    ui_CardCargo = NULL;
    ui_cargoTitle = NULL;
    ui_cargoValue = NULL;
    ui_CardDest = NULL;
    ui_destTitle = NULL;
    ui_destValue = NULL;
    ui_CardReward = NULL;
    ui_rewardTitle = NULL;
    ui_rewardValue = NULL;
    ui_CardDamage = NULL;
    ui_damageTitle = NULL;
    ui_damageValue = NULL;
    ui_TabBarPanel3 = NULL;
    ui_BtnNavDriving3 = NULL;
    ui_LblNavDriving3 = NULL;
    ui_BtnNavCtrl3 = NULL;
    ui_LblNavCtrl3 = NULL;
    ui_BtnNavTruck3 = NULL;
    ui_LblNavTruck3 = NULL;
    ui_BtnNavJob3 = NULL;
    ui_LblNavJob3 = NULL;
    ui_HeaderPanel3 = NULL;
    ui_StatusLabel3 = NULL;
    ui_TitleLabel4 = NULL;

}
