// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef UI_SCREENDRIVING_H
#define UI_SCREENDRIVING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDriving
extern void ui_ScreenDriving_screen_init(void);
extern void ui_ScreenDriving_screen_destroy(void);
extern lv_obj_t * ui_ScreenDriving;
extern lv_obj_t * ui_HeaderPanel;
extern lv_obj_t * ui_TitleLabel;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_TabBarPanel;
extern lv_obj_t * ui_BtnNavDriving;
extern lv_obj_t * ui_LblNavDriving;
extern void ui_event_BtnNavCtrl1(lv_event_t * e);
extern lv_obj_t * ui_BtnNavCtrl1;
extern lv_obj_t * ui_LblNavCtrl1;
extern void ui_event_BtnNavTruck(lv_event_t * e);
extern lv_obj_t * ui_BtnNavTruck;
extern lv_obj_t * ui_LblNavTruck;
extern void ui_event_BtnNavJob(lv_event_t * e);
extern lv_obj_t * ui_BtnNavJob;
extern lv_obj_t * ui_LblNavJob;
extern lv_obj_t * ui_SpeedArc;
extern lv_obj_t * ui_SpeedValueLabel;
extern lv_obj_t * ui_SpeedUnitLabel;
extern lv_obj_t * ui_RPMGroup;
extern lv_obj_t * ui_RPMLabel;
extern lv_obj_t * ui_RPMValueLabel;
extern lv_obj_t * ui_FuelGroup;
extern lv_obj_t * ui_FuelLabel;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_GearIndicator;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_DistIndicator;
extern lv_obj_t * ui_DistLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScrDriving;
extern lv_obj_t * uic_HeaderPanel;
extern lv_obj_t * uic_BtnNavCtrl;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

