// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#include "ui.h"

lv_obj_t * ui_ScreenTruck = NULL;
lv_obj_t * ui_HeaderPanel2 = NULL;
lv_obj_t * ui_TitleLabel2 = NULL;
lv_obj_t * ui_StatusLabel2 = NULL;
lv_obj_t * ui_TabBarPanel2 = NULL;
lv_obj_t * ui_BtnNavDriving2 = NULL;
lv_obj_t * ui_LblNavDriving2 = NULL;
lv_obj_t * ui_BtnNavCtrl2 = NULL;
lv_obj_t * ui_LblNavCtrl2 = NULL;
lv_obj_t * ui_BtnNavTruck2 = NULL;
lv_obj_t * ui_LblNavTruck2 = NULL;
lv_obj_t * ui_BtnNavJob2 = NULL;
lv_obj_t * ui_LblNavJob2 = NULL;
lv_obj_t * ui_TruckVisual = NULL;
lv_obj_t * ui_CabinBody = NULL;
lv_obj_t * ui_ChassisBody = NULL;
lv_obj_t * ui_EngineBlock = NULL;
lv_obj_t * ui_TransBlock = NULL;
lv_obj_t * ui_TrailerBody = NULL;
lv_obj_t * ui_WheelFL = NULL;
lv_obj_t * ui_WheelFR = NULL;
lv_obj_t * ui_WheelML = NULL;
lv_obj_t * ui_WheelMR = NULL;
lv_obj_t * ui_WheelRL = NULL;
lv_obj_t * ui_WheelRR = NULL;
lv_obj_t * ui_MotorValue = NULL;
lv_obj_t * ui_TransTitle = NULL;
lv_obj_t * ui_TransValue = NULL;
lv_obj_t * ui_MotorTitle = NULL;
lv_obj_t * ui_CabinTitle = NULL;
lv_obj_t * ui_CabinValue = NULL;
lv_obj_t * ui_ChassisTitle = NULL;
lv_obj_t * ui_ChassisValue = NULL;
lv_obj_t * ui_TrailerTitle = NULL;
lv_obj_t * ui_TrailerValue = NULL;
// event funtions
void ui_event_BtnNavDriving2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenDriving, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenDriving_screen_init);
    }
}

void ui_event_BtnNavCtrl2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenControls, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenControls_screen_init);
    }
}

void ui_event_BtnNavJob2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenJob, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenJob_screen_init);
    }
}

// build funtions

void ui_ScreenTruck_screen_init(void)
{
    ui_ScreenTruck = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenTruck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenTruck, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenTruck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderPanel2 = lv_obj_create(ui_ScreenTruck);
    lv_obj_set_width(ui_HeaderPanel2, 800);
    lv_obj_set_height(ui_HeaderPanel2, 60);
    lv_obj_set_align(ui_HeaderPanel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HeaderPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaderPanel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaderPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel2 = lv_label_create(ui_HeaderPanel2);
    lv_obj_set_width(ui_TitleLabel2, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_TitleLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel2, 30);
    lv_obj_set_y(ui_TitleLabel2, 0);
    lv_obj_set_align(ui_TitleLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TitleLabel2, "TRUCK-ESP32-CLUSTER v1.0\n");
    lv_obj_set_style_text_color(ui_TitleLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitleLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLabel2, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel2 = lv_label_create(ui_HeaderPanel2);
    lv_obj_set_width(ui_StatusLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel2, -30);
    lv_obj_set_y(ui_StatusLabel2, 0);
    lv_obj_set_align(ui_StatusLabel2, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_StatusLabel2, "RTOS LINK ACTIVE");
    lv_obj_set_style_text_color(ui_StatusLabel2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel2, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabBarPanel2 = lv_obj_create(ui_ScreenTruck);
    lv_obj_set_width(ui_TabBarPanel2, 800);
    lv_obj_set_height(ui_TabBarPanel2, 75);
    lv_obj_set_align(ui_TabBarPanel2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabBarPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabBarPanel2, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabBarPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabBarPanel2, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabBarPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabBarPanel2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavDriving2 = lv_btn_create(ui_TabBarPanel2);
    lv_obj_set_width(ui_BtnNavDriving2, 200);
    lv_obj_set_height(ui_BtnNavDriving2, 75);
    lv_obj_set_align(ui_BtnNavDriving2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavDriving2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavDriving2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavDriving2, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavDriving2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavDriving2 = lv_label_create(ui_BtnNavDriving2);
    lv_obj_set_width(ui_LblNavDriving2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavDriving2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavDriving2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavDriving2, "DRIVING");
    lv_obj_set_style_text_color(ui_LblNavDriving2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavDriving2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavDriving2, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavCtrl2 = lv_btn_create(ui_TabBarPanel2);
    lv_obj_set_width(ui_BtnNavCtrl2, 200);
    lv_obj_set_height(ui_BtnNavCtrl2, 75);
    lv_obj_set_x(ui_BtnNavCtrl2, 200);
    lv_obj_set_y(ui_BtnNavCtrl2, 0);
    lv_obj_set_align(ui_BtnNavCtrl2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavCtrl2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavCtrl2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavCtrl2, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavCtrl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavCtrl2 = lv_label_create(ui_BtnNavCtrl2);
    lv_obj_set_width(ui_LblNavCtrl2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavCtrl2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavCtrl2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavCtrl2, "CTRL");
    lv_obj_set_style_text_color(ui_LblNavCtrl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavCtrl2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavCtrl2, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavTruck2 = lv_btn_create(ui_TabBarPanel2);
    lv_obj_set_width(ui_BtnNavTruck2, 200);
    lv_obj_set_height(ui_BtnNavTruck2, 75);
    lv_obj_set_x(ui_BtnNavTruck2, 400);
    lv_obj_set_y(ui_BtnNavTruck2, 0);
    lv_obj_set_align(ui_BtnNavTruck2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavTruck2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavTruck2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavTruck2, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavTruck2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavTruck2 = lv_label_create(ui_BtnNavTruck2);
    lv_obj_set_width(ui_LblNavTruck2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavTruck2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavTruck2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavTruck2, "TRUCK");
    lv_obj_set_style_text_color(ui_LblNavTruck2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavTruck2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavTruck2, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavJob2 = lv_btn_create(ui_TabBarPanel2);
    lv_obj_set_width(ui_BtnNavJob2, 200);
    lv_obj_set_height(ui_BtnNavJob2, 75);
    lv_obj_set_x(ui_BtnNavJob2, 600);
    lv_obj_set_y(ui_BtnNavJob2, 0);
    lv_obj_set_align(ui_BtnNavJob2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavJob2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavJob2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavJob2, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavJob2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavJob2 = lv_label_create(ui_BtnNavJob2);
    lv_obj_set_width(ui_LblNavJob2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavJob2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavJob2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavJob2, "JOB");
    lv_obj_set_style_text_color(ui_LblNavJob2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavJob2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavJob2, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TruckVisual = lv_obj_create(ui_ScreenTruck);
    lv_obj_remove_style_all(ui_TruckVisual);
    lv_obj_set_width(ui_TruckVisual, 200);
    lv_obj_set_height(ui_TruckVisual, 400);
    lv_obj_set_x(ui_TruckVisual, 0);
    lv_obj_set_y(ui_TruckVisual, -30);
    lv_obj_set_align(ui_TruckVisual, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TruckVisual, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CabinBody = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_CabinBody, 84);
    lv_obj_set_height(ui_CabinBody, 95);
    lv_obj_set_x(ui_CabinBody, 0);
    lv_obj_set_y(ui_CabinBody, -87);
    lv_obj_set_align(ui_CabinBody, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CabinBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CabinBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CabinBody, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CabinBody, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CabinBody, lv_color_hex(0x00C14F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CabinBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CabinBody, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChassisBody = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_ChassisBody, 60);
    lv_obj_set_height(ui_ChassisBody, 140);
    lv_obj_set_x(ui_ChassisBody, 0);
    lv_obj_set_y(ui_ChassisBody, 25);
    lv_obj_set_align(ui_ChassisBody, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChassisBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ChassisBody, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChassisBody, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChassisBody, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChassisBody, lv_color_hex(0x00C14F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChassisBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChassisBody, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EngineBlock = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_EngineBlock, 36);
    lv_obj_set_height(ui_EngineBlock, 40);
    lv_obj_set_x(ui_EngineBlock, 0);
    lv_obj_set_y(ui_EngineBlock, -95);
    lv_obj_set_align(ui_EngineBlock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EngineBlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_EngineBlock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_EngineBlock, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EngineBlock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_EngineBlock, lv_color_hex(0x00C14F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_EngineBlock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_EngineBlock, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TransBlock = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_TransBlock, 24);
    lv_obj_set_height(ui_TransBlock, 45);
    lv_obj_set_x(ui_TransBlock, 0);
    lv_obj_set_y(ui_TransBlock, 17);
    lv_obj_set_align(ui_TransBlock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TransBlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TransBlock, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TransBlock, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TransBlock, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TransBlock, lv_color_hex(0x00C14F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TransBlock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TransBlock, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrailerBody = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_TrailerBody, 140);
    lv_obj_set_height(ui_TrailerBody, 220);
    lv_obj_set_x(ui_TrailerBody, 0);
    lv_obj_set_y(ui_TrailerBody, 75);
    lv_obj_set_align(ui_TrailerBody, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TrailerBody, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TrailerBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TrailerBody, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TrailerBody, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TrailerBody, lv_color_hex(0x00C14F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TrailerBody, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TrailerBody, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelFL = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelFL, 20);
    lv_obj_set_height(ui_WheelFL, 42);
    lv_obj_set_x(ui_WheelFL, -60);
    lv_obj_set_y(ui_WheelFL, -100);
    lv_obj_set_align(ui_WheelFL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelFL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelFL, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelFL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelFL, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelFL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelFL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelFR = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelFR, 20);
    lv_obj_set_height(ui_WheelFR, 42);
    lv_obj_set_x(ui_WheelFR, 60);
    lv_obj_set_y(ui_WheelFR, -100);
    lv_obj_set_align(ui_WheelFR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelFR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelFR, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelFR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelFR, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelFR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelFR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelML = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelML, 20);
    lv_obj_set_height(ui_WheelML, 42);
    lv_obj_set_x(ui_WheelML, -60);
    lv_obj_set_y(ui_WheelML, 20);
    lv_obj_set_align(ui_WheelML, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelML, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelML, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelML, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelML, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelML, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelML, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelMR = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelMR, 20);
    lv_obj_set_height(ui_WheelMR, 42);
    lv_obj_set_x(ui_WheelMR, 60);
    lv_obj_set_y(ui_WheelMR, 20);
    lv_obj_set_align(ui_WheelMR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelMR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelMR, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelMR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelMR, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelMR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelMR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelRL = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelRL, 20);
    lv_obj_set_height(ui_WheelRL, 42);
    lv_obj_set_x(ui_WheelRL, -60);
    lv_obj_set_y(ui_WheelRL, 90);
    lv_obj_set_align(ui_WheelRL, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelRL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelRL, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelRL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelRL, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelRL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelRL, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WheelRR = lv_obj_create(ui_TruckVisual);
    lv_obj_set_width(ui_WheelRR, 20);
    lv_obj_set_height(ui_WheelRR, 42);
    lv_obj_set_x(ui_WheelRR, 60);
    lv_obj_set_y(ui_WheelRR, 90);
    lv_obj_set_align(ui_WheelRR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WheelRR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WheelRR, lv_color_hex(0x19191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WheelRR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WheelRR, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WheelRR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WheelRR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorValue = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_MotorValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorValue, 150);
    lv_obj_set_y(ui_MotorValue, -105);
    lv_obj_set_align(ui_MotorValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MotorValue, "1.2%");
    lv_obj_set_style_text_color(ui_MotorValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TransTitle = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_TransTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TransTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TransTitle, 150);
    lv_obj_set_y(ui_TransTitle, -55);
    lv_obj_set_align(ui_TransTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TransTitle, "TRANSMISION");
    lv_obj_set_style_text_color(ui_TransTitle, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TransTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TransTitle, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TransValue = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_TransValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TransValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TransValue, 150);
    lv_obj_set_y(ui_TransValue, -25);
    lv_obj_set_align(ui_TransValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TransValue, "14.2%");
    lv_obj_set_style_text_color(ui_TransValue, lv_color_hex(0xFFFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TransValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TransValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorTitle = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_MotorTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorTitle, 150);
    lv_obj_set_y(ui_MotorTitle, -135);
    lv_obj_set_align(ui_MotorTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MotorTitle, "Motor");
    lv_obj_set_style_text_color(ui_MotorTitle, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorTitle, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CabinTitle = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_CabinTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CabinTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CabinTitle, 550);
    lv_obj_set_y(ui_CabinTitle, -105);
    lv_obj_set_align(ui_CabinTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CabinTitle, "CABIN");
    lv_obj_set_style_text_color(ui_CabinTitle, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CabinTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CabinTitle, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CabinValue = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_CabinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CabinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CabinValue, 550);
    lv_obj_set_y(ui_CabinValue, -70);
    lv_obj_set_align(ui_CabinValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CabinValue, "0.5%");
    lv_obj_set_style_text_color(ui_CabinValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CabinValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CabinValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChassisTitle = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_ChassisTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChassisTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChassisTitle, 550);
    lv_obj_set_y(ui_ChassisTitle, 50);
    lv_obj_set_align(ui_ChassisTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ChassisTitle, "CHASIS");
    lv_obj_set_style_text_color(ui_ChassisTitle, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChassisTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChassisTitle, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChassisValue = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_ChassisValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChassisValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChassisValue, 550);
    lv_obj_set_y(ui_ChassisValue, 80);
    lv_obj_set_align(ui_ChassisValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ChassisValue, "2.8%");
    lv_obj_set_style_text_color(ui_ChassisValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChassisValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChassisValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrailerTitle = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_TrailerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrailerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrailerTitle, 150);
    lv_obj_set_y(ui_TrailerTitle, 40);
    lv_obj_set_align(ui_TrailerTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrailerTitle, "TRAILER");
    lv_obj_set_style_text_color(ui_TrailerTitle, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrailerTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrailerTitle, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrailerValue = lv_label_create(ui_ScreenTruck);
    lv_obj_set_width(ui_TrailerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrailerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrailerValue, 150);
    lv_obj_set_y(ui_TrailerValue, 70);
    lv_obj_set_align(ui_TrailerValue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TrailerValue, "0.0%");
    lv_obj_set_style_text_color(ui_TrailerValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrailerValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrailerValue, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnNavDriving2, ui_event_BtnNavDriving2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavCtrl2, ui_event_BtnNavCtrl2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavJob2, ui_event_BtnNavJob2, LV_EVENT_ALL, NULL);

}

void ui_ScreenTruck_screen_destroy(void)
{
    if(ui_ScreenTruck) lv_obj_del(ui_ScreenTruck);

    // NULL screen variables
    ui_ScreenTruck = NULL;
    ui_HeaderPanel2 = NULL;
    ui_TitleLabel2 = NULL;
    ui_StatusLabel2 = NULL;
    ui_TabBarPanel2 = NULL;
    ui_BtnNavDriving2 = NULL;
    ui_LblNavDriving2 = NULL;
    ui_BtnNavCtrl2 = NULL;
    ui_LblNavCtrl2 = NULL;
    ui_BtnNavTruck2 = NULL;
    ui_LblNavTruck2 = NULL;
    ui_BtnNavJob2 = NULL;
    ui_LblNavJob2 = NULL;
    ui_TruckVisual = NULL;
    ui_CabinBody = NULL;
    ui_ChassisBody = NULL;
    ui_EngineBlock = NULL;
    ui_TransBlock = NULL;
    ui_TrailerBody = NULL;
    ui_WheelFL = NULL;
    ui_WheelFR = NULL;
    ui_WheelML = NULL;
    ui_WheelMR = NULL;
    ui_WheelRL = NULL;
    ui_WheelRR = NULL;
    ui_MotorValue = NULL;
    ui_TransTitle = NULL;
    ui_TransValue = NULL;
    ui_MotorTitle = NULL;
    ui_CabinTitle = NULL;
    ui_CabinValue = NULL;
    ui_ChassisTitle = NULL;
    ui_ChassisValue = NULL;
    ui_TrailerTitle = NULL;
    ui_TrailerValue = NULL;

}
