// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#ifndef UI_SCREENCONTROLS_H
#define UI_SCREENCONTROLS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenControls
extern void ui_ScreenControls_screen_init(void);
extern void ui_ScreenControls_screen_destroy(void);
extern lv_obj_t * ui_ScreenControls;
extern lv_obj_t * ui_HeaderPanel1;
extern lv_obj_t * ui_TitleLabel1;
extern lv_obj_t * ui_StatusLabel1;
extern lv_obj_t * ui_TabBarPanel1;
extern void ui_event_BtnNavDriving1(lv_event_t * e);
extern lv_obj_t * ui_BtnNavDriving1;
extern lv_obj_t * ui_LblNavDriving1;
extern lv_obj_t * ui_BtnNavCtrl;
extern lv_obj_t * ui_LblNavCtrl;
extern void ui_event_BtnNavTruck1(lv_event_t * e);
extern lv_obj_t * ui_BtnNavTruck1;
extern lv_obj_t * ui_LblNavTruck1;
extern void ui_event_BtnNavJob1(lv_event_t * e);
extern lv_obj_t * ui_BtnNavJob1;
extern lv_obj_t * ui_LblNavJob1;
extern lv_obj_t * ui_ControlsContainer;
extern lv_obj_t * ui_LightsPanel;
extern void ui_event_BtnLights(lv_event_t * e);
extern lv_obj_t * ui_BtnLights;
extern lv_obj_t * ui_ImgLights;
extern lv_obj_t * ui_LblLigths;
extern void ui_event_BtnHighBeam(lv_event_t * e);
extern lv_obj_t * ui_BtnHighBeam;
extern lv_obj_t * ui_ImgBeam;
extern lv_obj_t * ui_LblBeam;
extern lv_obj_t * ui_GearSelector;
extern void ui_event_LabelR(lv_event_t * e);
extern lv_obj_t * ui_LabelR;
extern void ui_event_LabelN(lv_event_t * e);
extern lv_obj_t * ui_LabelN;
extern void ui_event_LabelD(lv_event_t * e);
extern lv_obj_t * ui_LabelD;
extern lv_obj_t * ui_UtilityPanel;
extern void ui_event_BtnWipers(lv_event_t * e);
extern lv_obj_t * ui_BtnWipers;
extern lv_obj_t * ui_ImgWipers;
extern lv_obj_t * ui_LblWipers;
extern void ui_event_BtnHazards(lv_event_t * e);
extern lv_obj_t * ui_BtnHazards;
extern lv_obj_t * ui_ImgHazards;
extern lv_obj_t * ui_LblHazards;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

