// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Eurotruck_Steering_Wheel

#include "ui.h"

lv_obj_t * uic_BtnNavCtrl;
lv_obj_t * uic_HeaderPanel;
lv_obj_t * uic_ScrDriving;
lv_obj_t * ui_ScreenDriving = NULL;
lv_obj_t * ui_HeaderPanel = NULL;
lv_obj_t * ui_TitleLabel = NULL;
lv_obj_t * ui_StatusLabel = NULL;
lv_obj_t * ui_TabBarPanel = NULL;
lv_obj_t * ui_BtnNavDriving = NULL;
lv_obj_t * ui_LblNavDriving = NULL;
lv_obj_t * ui_BtnNavCtrl1 = NULL;
lv_obj_t * ui_LblNavCtrl1 = NULL;
lv_obj_t * ui_BtnNavTruck = NULL;
lv_obj_t * ui_LblNavTruck = NULL;
lv_obj_t * ui_BtnNavJob = NULL;
lv_obj_t * ui_LblNavJob = NULL;
lv_obj_t * ui_SpeedArc = NULL;
lv_obj_t * ui_SpeedValueLabel = NULL;
lv_obj_t * ui_SpeedUnitLabel = NULL;
lv_obj_t * ui_RPMGroup = NULL;
lv_obj_t * ui_RPMLabel = NULL;
lv_obj_t * ui_RPMValueLabel = NULL;
lv_obj_t * ui_FuelGroup = NULL;
lv_obj_t * ui_FuelLabel = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_GearIndicator = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_DistIndicator = NULL;
lv_obj_t * ui_DistLabel = NULL;
// event funtions
void ui_event_BtnNavCtrl1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenControls, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenControls_screen_init);
    }
}

void ui_event_BtnNavTruck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenTruck, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenTruck_screen_init);
    }
}

void ui_event_BtnNavJob(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenJob, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_ScreenJob_screen_init);
    }
}

// build funtions

void ui_ScreenDriving_screen_init(void)
{
    ui_ScreenDriving = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenDriving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenDriving, lv_color_hex(0x0C0C0C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenDriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeaderPanel = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_HeaderPanel, 800);
    lv_obj_set_height(ui_HeaderPanel, 60);
    lv_obj_set_align(ui_HeaderPanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HeaderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeaderPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeaderPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TitleLabel = lv_label_create(ui_HeaderPanel);
    lv_obj_set_width(ui_TitleLabel, LV_SIZE_CONTENT);   /// 0
    lv_obj_set_height(ui_TitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TitleLabel, 30);
    lv_obj_set_y(ui_TitleLabel, 0);
    lv_obj_set_align(ui_TitleLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TitleLabel, "TRUCK-ESP32-CLUSTER v1.0\n");
    lv_obj_set_style_text_color(ui_TitleLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TitleLabel, &ui_font_FontUILarge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusLabel = lv_label_create(ui_HeaderPanel);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StatusLabel, -30);
    lv_obj_set_y(ui_StatusLabel, 0);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_StatusLabel, "RTOS LINK ACTIVE");
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StatusLabel, &ui_font_FontUISmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabBarPanel = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_TabBarPanel, 800);
    lv_obj_set_height(ui_TabBarPanel, 75);
    lv_obj_set_align(ui_TabBarPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabBarPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TabBarPanel, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TabBarPanel, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TabBarPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TabBarPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavDriving = lv_btn_create(ui_TabBarPanel);
    lv_obj_set_width(ui_BtnNavDriving, 200);
    lv_obj_set_height(ui_BtnNavDriving, 75);
    lv_obj_set_align(ui_BtnNavDriving, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavDriving, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavDriving, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavDriving, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavDriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavDriving = lv_label_create(ui_BtnNavDriving);
    lv_obj_set_width(ui_LblNavDriving, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavDriving, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavDriving, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavDriving, "DRIVING");
    lv_obj_set_style_text_color(ui_LblNavDriving, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavDriving, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavDriving, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavCtrl1 = lv_btn_create(ui_TabBarPanel);
    lv_obj_set_width(ui_BtnNavCtrl1, 200);
    lv_obj_set_height(ui_BtnNavCtrl1, 75);
    lv_obj_set_x(ui_BtnNavCtrl1, 200);
    lv_obj_set_y(ui_BtnNavCtrl1, 0);
    lv_obj_set_align(ui_BtnNavCtrl1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavCtrl1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavCtrl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavCtrl1, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavCtrl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavCtrl1 = lv_label_create(ui_BtnNavCtrl1);
    lv_obj_set_width(ui_LblNavCtrl1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavCtrl1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavCtrl1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavCtrl1, "CTRL");
    lv_obj_set_style_text_color(ui_LblNavCtrl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavCtrl1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavCtrl1, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavTruck = lv_btn_create(ui_TabBarPanel);
    lv_obj_set_width(ui_BtnNavTruck, 200);
    lv_obj_set_height(ui_BtnNavTruck, 75);
    lv_obj_set_x(ui_BtnNavTruck, 400);
    lv_obj_set_y(ui_BtnNavTruck, 0);
    lv_obj_set_align(ui_BtnNavTruck, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavTruck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavTruck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavTruck, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavTruck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavTruck = lv_label_create(ui_BtnNavTruck);
    lv_obj_set_width(ui_LblNavTruck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavTruck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavTruck, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavTruck, "TRUCK");
    lv_obj_set_style_text_color(ui_LblNavTruck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavTruck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavTruck, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNavJob = lv_btn_create(ui_TabBarPanel);
    lv_obj_set_width(ui_BtnNavJob, 200);
    lv_obj_set_height(ui_BtnNavJob, 75);
    lv_obj_set_x(ui_BtnNavJob, 600);
    lv_obj_set_y(ui_BtnNavJob, 0);
    lv_obj_set_align(ui_BtnNavJob, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BtnNavJob, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNavJob, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnNavJob, lv_color_hex(0x0A0B0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNavJob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LblNavJob = lv_label_create(ui_BtnNavJob);
    lv_obj_set_width(ui_LblNavJob, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LblNavJob, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LblNavJob, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LblNavJob, "JOB");
    lv_obj_set_style_text_color(ui_LblNavJob, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LblNavJob, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LblNavJob, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedArc = lv_arc_create(ui_ScreenDriving);
    lv_obj_set_width(ui_SpeedArc, 300);
    lv_obj_set_height(ui_SpeedArc, 300);
    lv_obj_set_x(ui_SpeedArc, 0);
    lv_obj_set_y(ui_SpeedArc, -20);
    lv_obj_set_align(ui_SpeedArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_SpeedArc, 0, 200);
    lv_arc_set_value(ui_SpeedArc, 85);
    lv_arc_set_bg_angles(ui_SpeedArc, 0, 270);
    lv_arc_set_rotation(ui_SpeedArc, 135);
    lv_obj_set_style_arc_color(ui_SpeedArc, lv_color_hex(0x20222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedArc, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpeedArc, lv_color_hex(0x0096FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpeedArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpeedArc, 12, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeedArc, lv_color_hex(0xDB1111), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_SpeedValueLabel = lv_label_create(ui_SpeedArc);
    lv_obj_set_width(ui_SpeedValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedValueLabel, 0);
    lv_obj_set_y(ui_SpeedValueLabel, -10);
    lv_obj_set_align(ui_SpeedValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValueLabel, "50");
    lv_obj_set_style_text_color(ui_SpeedValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValueLabel, &ui_font_FontSpeedHuge, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedUnitLabel = lv_label_create(ui_SpeedArc);
    lv_obj_set_width(ui_SpeedUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedUnitLabel, 0);
    lv_obj_set_y(ui_SpeedUnitLabel, 75);
    lv_obj_set_align(ui_SpeedUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedUnitLabel, "MPH");
    lv_obj_set_style_text_color(ui_SpeedUnitLabel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedUnitLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedUnitLabel, &ui_font_FontUIRegular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMGroup = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_RPMGroup, 200);
    lv_obj_set_height(ui_RPMGroup, 120);
    lv_obj_set_x(ui_RPMGroup, 30);
    lv_obj_set_y(ui_RPMGroup, -30);
    lv_obj_set_align(ui_RPMGroup, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_RPMGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RPMGroup, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMGroup, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMLabel = lv_label_create(ui_RPMGroup);
    lv_obj_set_width(ui_RPMLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMLabel, 15);
    lv_obj_set_y(ui_RPMLabel, 10);
    lv_label_set_text(ui_RPMLabel, "ENGINE RPM");
    lv_obj_set_style_text_color(ui_RPMLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMLabel, &ui_font_FontUITiny, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMValueLabel = lv_label_create(ui_RPMGroup);
    lv_obj_set_width(ui_RPMValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RPMValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RPMValueLabel, 0);
    lv_obj_set_y(ui_RPMValueLabel, 15);
    lv_obj_set_align(ui_RPMValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RPMValueLabel, "1250");
    lv_obj_set_style_text_color(ui_RPMValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RPMValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RPMValueLabel, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelGroup = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_FuelGroup, 200);
    lv_obj_set_height(ui_FuelGroup, 120);
    lv_obj_set_x(ui_FuelGroup, -30);
    lv_obj_set_y(ui_FuelGroup, -30);
    lv_obj_set_align(ui_FuelGroup, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_FuelGroup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FuelGroup, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FuelGroup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FuelGroup, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelLabel = lv_label_create(ui_FuelGroup);
    lv_obj_set_width(ui_FuelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelLabel, 15);
    lv_obj_set_y(ui_FuelLabel, 10);
    lv_label_set_text(ui_FuelLabel, "FUEL LEVEL");
    lv_obj_set_style_text_color(ui_FuelLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FuelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FuelLabel, &ui_font_FontUITiny, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_FuelGroup);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, 15);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "85%");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearIndicator = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_GearIndicator, 80);
    lv_obj_set_height(ui_GearIndicator, 65);
    lv_obj_set_x(ui_GearIndicator, -110);
    lv_obj_set_y(ui_GearIndicator, 135);
    lv_obj_set_align(ui_GearIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GearIndicator, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GearIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearIndicator, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GearIndicator, lv_color_hex(0x0096FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GearIndicator, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_GearIndicator);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "12");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x60FF78), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistIndicator = lv_obj_create(ui_ScreenDriving);
    lv_obj_set_width(ui_DistIndicator, 200);
    lv_obj_set_height(ui_DistIndicator, 65);
    lv_obj_set_x(ui_DistIndicator, 110);
    lv_obj_set_y(ui_DistIndicator, 135);
    lv_obj_set_align(ui_DistIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DistIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DistIndicator, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DistIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DistIndicator, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistLabel = lv_label_create(ui_DistIndicator);
    lv_obj_set_width(ui_DistLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DistLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DistLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistLabel, "452 mi");
    lv_obj_set_style_text_color(ui_DistLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DistLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DistLabel, &ui_font_FontDataMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BtnNavCtrl1, ui_event_BtnNavCtrl1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavTruck, ui_event_BtnNavTruck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNavJob, ui_event_BtnNavJob, LV_EVENT_ALL, NULL);
    uic_ScrDriving = ui_ScreenDriving;
    uic_HeaderPanel = ui_HeaderPanel;
    uic_BtnNavCtrl = ui_BtnNavCtrl1;

}

void ui_ScreenDriving_screen_destroy(void)
{
    if(ui_ScreenDriving) lv_obj_del(ui_ScreenDriving);

    // NULL screen variables
    uic_ScrDriving = NULL;
    ui_ScreenDriving = NULL;
    uic_HeaderPanel = NULL;
    ui_HeaderPanel = NULL;
    ui_TitleLabel = NULL;
    ui_StatusLabel = NULL;
    ui_TabBarPanel = NULL;
    ui_BtnNavDriving = NULL;
    ui_LblNavDriving = NULL;
    uic_BtnNavCtrl = NULL;
    ui_BtnNavCtrl1 = NULL;
    ui_LblNavCtrl1 = NULL;
    ui_BtnNavTruck = NULL;
    ui_LblNavTruck = NULL;
    ui_BtnNavJob = NULL;
    ui_LblNavJob = NULL;
    ui_SpeedArc = NULL;
    ui_SpeedValueLabel = NULL;
    ui_SpeedUnitLabel = NULL;
    ui_RPMGroup = NULL;
    ui_RPMLabel = NULL;
    ui_RPMValueLabel = NULL;
    ui_FuelGroup = NULL;
    ui_FuelLabel = NULL;
    ui_Label9 = NULL;
    ui_GearIndicator = NULL;
    ui_Label10 = NULL;
    ui_DistIndicator = NULL;
    ui_DistLabel = NULL;

}
