// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef _MONITOR_UI_H
#define _MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
// Declaradas como mutable (sin const) porque _load() escribe .data en PSRAM en runtime.
extern lv_img_dsc_t ui_img_mty_noche_png;
extern lv_img_dsc_t ui_img_mty_amanecer_png;
extern lv_img_dsc_t ui_img_mty_dia_png;
extern lv_img_dsc_t ui_img_mty_atardecer_png;

// FONTS
LV_FONT_DECLARE(ui_font_fontBig);
LV_FONT_DECLARE(ui_font_fontMedium);
LV_FONT_DECLARE(ui_font_fontSmall);

///////////////////// SCREENS ////////////////////
// Dashboard primero — las demás pantallas lo referencian en sus event handlers.
#include "ui_screenDashboard.h"
#include "ui_screenMorning.h"
#include "ui_screenDay.h"
#include "ui_screenDown.h"
#include "ui_screenNight.h"
#include "ui_screenSerial.h"

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
