// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef _UI_COMP_COMCARG_H
#define _UI_COMP_COMCARG_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT comCarg
#define UI_COMP_COMCARG_COMCARG 0
#define UI_COMP_COMCARG_LBLCOMNAME 1
#define _UI_COMP_COMCARG_NUM 2
lv_obj_t * ui_comCarg_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
