// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

// COMPONENT comCarg

lv_obj_t * ui_comCarg_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_comCarg;
    cui_comCarg = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_comCarg, 180);
    lv_obj_set_height(cui_comCarg, 180);
    lv_obj_set_align(cui_comCarg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_comCarg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_comCarg, lv_color_hex(0x474747), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_comCarg, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_comCarg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_comCarg, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lblComName;
    cui_lblComName = lv_label_create(cui_comCarg);
    lv_obj_set_width(cui_lblComName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lblComName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_lblComName, LV_ALIGN_CENTER);
    lv_label_set_text(cui_lblComName, "COMx");
    lv_obj_set_style_text_color(cui_lblComName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_lblComName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_lblComName, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_COMCARG_NUM);
    children[UI_COMP_COMCARG_COMCARG] = cui_comCarg;
    children[UI_COMP_COMCARG_LBLCOMNAME] = cui_lblComName;
    lv_obj_add_event_cb(cui_comCarg, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_comCarg, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_comCarg_create_hook(cui_comCarg);
    return cui_comCarg;
}

