// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Temporal

#include "ui.h"


// IMAGE DATA: assets/monitor_bg.png
lv_img_dsc_t ui_img_monitor_bg_png = {
    .header.always_zero = 0,
    .header.w = 800,
    .header.h = 480,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_monitor_bg_png_load()
{
    ui_img_monitor_bg_png.data = UI_LOAD_IMAGE("S:assets/ui_img_monitor_bg_png.bin", 1152000);
    ui_img_monitor_bg_png.data_size = 1152000;
}
