// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENDOWN_H
#define UI_SCREENDOWN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenDown
extern void ui_screenDown_screen_init(void);
extern void ui_screenDown_screen_destroy(void);
extern void ui_event_screenDown(lv_event_t * e);
extern lv_obj_t * ui_screenDown;
extern lv_obj_t * ui_bgImg3;
extern lv_obj_t * ui_timeTempWidget3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_labelHour3;
extern lv_obj_t * ui_lblTime3;
extern lv_obj_t * ui_labelTemp3;
extern void ui_event_monitorBtn3(lv_event_t * e);
extern lv_obj_t * ui_monitorBtn3;
extern lv_obj_t * ui_labelMonitor3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

