// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENNIGHT_H
#define UI_SCREENNIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenNight
extern void ui_screenNight_screen_init(void);
extern void ui_screenNight_screen_destroy(void);
extern void ui_event_screenNight(lv_event_t * e);
extern lv_obj_t * ui_screenNight;
extern lv_obj_t * ui_bgImg1;
extern lv_obj_t * ui_timeTempWidget1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_labelHour1;
extern lv_obj_t * ui_lblTime1;
extern lv_obj_t * ui_labelTemp1;
extern void ui_event_monitorBtn1(lv_event_t * e);
extern lv_obj_t * ui_monitorBtn1;
extern lv_obj_t * ui_labelMonitor1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

