// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenNight = NULL;
lv_obj_t * ui_bgImg1 = NULL;
lv_obj_t * ui_timeTempWidget1 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_labelHour1 = NULL;
lv_obj_t * ui_lblTime1 = NULL;
lv_obj_t * ui_labelTemp1 = NULL;
lv_obj_t * ui_monitorBtn1 = NULL;
lv_obj_t * ui_labelMonitor1 = NULL;
// event funtions
void ui_event_screenNight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

void ui_event_monitorBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

// build funtions

void ui_screenNight_screen_init(void)
{
    ui_screenNight = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenNight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgImg1 = lv_img_create(ui_screenNight);
    lv_img_set_src(ui_bgImg1, &ui_img_mty_noche_png);
    lv_obj_set_width(ui_bgImg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgImg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgImg1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeTempWidget1 = lv_obj_create(ui_screenNight);
    lv_obj_set_width(ui_timeTempWidget1, 240);
    lv_obj_set_height(ui_timeTempWidget1, 140);
    lv_obj_set_x(ui_timeTempWidget1, -20);
    lv_obj_set_y(ui_timeTempWidget1, -100);
    lv_obj_set_align(ui_timeTempWidget1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_timeTempWidget1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_timeTempWidget1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeTempWidget1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeTempWidget1, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeTempWidget1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeTempWidget1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeTempWidget1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_timeTempWidget1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelHour1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_labelHour1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHour1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelHour1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHour1, "11:30");
    lv_obj_set_style_text_color(ui_labelHour1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelHour1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelHour1, &ui_font_fontBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblTime1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime1, "PM");
    lv_obj_set_style_text_color(ui_lblTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime1, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp1 = lv_label_create(ui_timeTempWidget1);
    lv_obj_set_width(ui_labelTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp1, "32°C Monterrey, NL");
    lv_obj_set_style_text_color(ui_labelTemp1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp1, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitorBtn1 = lv_btn_create(ui_screenNight);
    lv_obj_set_width(ui_monitorBtn1, 240);
    lv_obj_set_height(ui_monitorBtn1, 60);
    lv_obj_set_x(ui_monitorBtn1, -20);
    lv_obj_set_y(ui_monitorBtn1, -20);
    lv_obj_set_align(ui_monitorBtn1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_monitorBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_monitorBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_monitorBtn1, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monitorBtn1, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_monitorBtn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_monitorBtn1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monitorBtn1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMonitor1 = lv_label_create(ui_monitorBtn1);
    lv_obj_set_width(ui_labelMonitor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMonitor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelMonitor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMonitor1, "Monitor");
    lv_obj_set_style_text_font(ui_labelMonitor1, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_monitorBtn1, ui_event_monitorBtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenNight, ui_event_screenNight, LV_EVENT_ALL, NULL);

}

void ui_screenNight_screen_destroy(void)
{
    if(ui_screenNight) lv_obj_del(ui_screenNight);

    // NULL screen variables
    ui_screenNight = NULL;
    ui_bgImg1 = NULL;
    ui_timeTempWidget1 = NULL;
    ui_Container2 = NULL;
    ui_labelHour1 = NULL;
    ui_lblTime1 = NULL;
    ui_labelTemp1 = NULL;
    ui_monitorBtn1 = NULL;
    ui_labelMonitor1 = NULL;

}
