// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenDown = NULL;
lv_obj_t * ui_bgImg3 = NULL;
lv_obj_t * ui_timeTempWidget3 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_labelHour3 = NULL;
lv_obj_t * ui_lblTime3 = NULL;
lv_obj_t * ui_labelTemp3 = NULL;
lv_obj_t * ui_monitorBtn3 = NULL;
lv_obj_t * ui_labelMonitor3 = NULL;
// event funtions
void ui_event_screenDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

void ui_event_monitorBtn3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

// build funtions

void ui_screenDown_screen_init(void)
{
    ui_screenDown = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgImg3 = lv_img_create(ui_screenDown);
    lv_img_set_src(ui_bgImg3, &ui_img_mty_atardecer_png);
    lv_obj_set_width(ui_bgImg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgImg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgImg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgImg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgImg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeTempWidget3 = lv_obj_create(ui_screenDown);
    lv_obj_set_width(ui_timeTempWidget3, 240);
    lv_obj_set_height(ui_timeTempWidget3, 140);
    lv_obj_set_x(ui_timeTempWidget3, -20);
    lv_obj_set_y(ui_timeTempWidget3, -100);
    lv_obj_set_align(ui_timeTempWidget3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_timeTempWidget3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_timeTempWidget3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeTempWidget3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeTempWidget3, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeTempWidget3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeTempWidget3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeTempWidget3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_timeTempWidget3);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelHour3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_labelHour3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHour3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelHour3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHour3, "7:30");
    lv_obj_set_style_text_color(ui_labelHour3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelHour3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelHour3, &ui_font_fontBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime3 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_lblTime3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTime3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime3, "PM");
    lv_obj_set_style_text_color(ui_lblTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime3, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp3 = lv_label_create(ui_timeTempWidget3);
    lv_obj_set_width(ui_labelTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelTemp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp3, "32°C Monterrey, NL");
    lv_obj_set_style_text_color(ui_labelTemp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp3, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitorBtn3 = lv_btn_create(ui_screenDown);
    lv_obj_set_width(ui_monitorBtn3, 240);
    lv_obj_set_height(ui_monitorBtn3, 60);
    lv_obj_set_x(ui_monitorBtn3, -20);
    lv_obj_set_y(ui_monitorBtn3, -20);
    lv_obj_set_align(ui_monitorBtn3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_monitorBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_monitorBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_monitorBtn3, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monitorBtn3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_monitorBtn3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_monitorBtn3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monitorBtn3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMonitor3 = lv_label_create(ui_monitorBtn3);
    lv_obj_set_width(ui_labelMonitor3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMonitor3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelMonitor3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMonitor3, "Monitor");
    lv_obj_set_style_text_font(ui_labelMonitor3, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_monitorBtn3, ui_event_monitorBtn3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenDown, ui_event_screenDown, LV_EVENT_ALL, NULL);

}

void ui_screenDown_screen_destroy(void)
{
    if(ui_screenDown) lv_obj_del(ui_screenDown);

    // NULL screen variables
    ui_screenDown = NULL;
    ui_bgImg3 = NULL;
    ui_timeTempWidget3 = NULL;
    ui_Container4 = NULL;
    ui_labelHour3 = NULL;
    ui_lblTime3 = NULL;
    ui_labelTemp3 = NULL;
    ui_monitorBtn3 = NULL;
    ui_labelMonitor3 = NULL;

}
