// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENMORNING_H
#define UI_SCREENMORNING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenMorning
extern void ui_screenMorning_screen_init(void);
extern void ui_screenMorning_screen_destroy(void);
extern void ui_event_screenMorning(lv_event_t * e);
extern lv_obj_t * ui_screenMorning;
extern lv_obj_t * ui_bgImg2;
extern lv_obj_t * ui_timeTempWidget2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_labelHour2;
extern lv_obj_t * ui_lblTime2;
extern lv_obj_t * ui_labelTemp2;
extern void ui_event_monitorBtn2(lv_event_t * e);
extern lv_obj_t * ui_monitorBtn2;
extern lv_obj_t * ui_labelMonitor2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

