// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENDASHBOARD_H
#define UI_SCREENDASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenDashboard
extern void ui_screenDashboard_screen_init(void);
extern void ui_screenDashboard_screen_destroy(void);
extern lv_obj_t * ui_screenDashboard;
extern lv_obj_t * ui_comContainer;
extern lv_obj_t * ui_lblTitleDash;
extern void ui_event_hubBtn(lv_event_t * e);
extern lv_obj_t * ui_hubBtn;
extern lv_obj_t * ui_lblBtn;
extern void ui_event_btConnectionSts(lv_event_t * e);
extern lv_obj_t * ui_btConnectionSts;
extern lv_obj_t * ui_btLbl;
extern lv_obj_t * ui_btSts;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

