// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenMorning = NULL;
lv_obj_t * ui_bgImg2 = NULL;
lv_obj_t * ui_timeTempWidget2 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_labelHour2 = NULL;
lv_obj_t * ui_lblTime2 = NULL;
lv_obj_t * ui_labelTemp2 = NULL;
lv_obj_t * ui_monitorBtn2 = NULL;
lv_obj_t * ui_labelMonitor2 = NULL;
// event funtions
void ui_event_screenMorning(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

void ui_event_monitorBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

// build funtions

void ui_screenMorning_screen_init(void)
{
    ui_screenMorning = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenMorning, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgImg2 = lv_img_create(ui_screenMorning);
    lv_img_set_src(ui_bgImg2, &ui_img_mty_amanecer_png);
    lv_obj_set_width(ui_bgImg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgImg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeTempWidget2 = lv_obj_create(ui_screenMorning);
    lv_obj_set_width(ui_timeTempWidget2, 240);
    lv_obj_set_height(ui_timeTempWidget2, 140);
    lv_obj_set_x(ui_timeTempWidget2, -20);
    lv_obj_set_y(ui_timeTempWidget2, -100);
    lv_obj_set_align(ui_timeTempWidget2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_timeTempWidget2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_timeTempWidget2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeTempWidget2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeTempWidget2, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeTempWidget2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeTempWidget2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeTempWidget2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_timeTempWidget2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelHour2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_labelHour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelHour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHour2, "6:00");
    lv_obj_set_style_text_color(ui_labelHour2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelHour2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelHour2, &ui_font_fontBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime2 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblTime2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTime2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime2, "AM");
    lv_obj_set_style_text_color(ui_lblTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime2, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp2 = lv_label_create(ui_timeTempWidget2);
    lv_obj_set_width(ui_labelTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp2, "32°C Monterrey, NL");
    lv_obj_set_style_text_color(ui_labelTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp2, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitorBtn2 = lv_btn_create(ui_screenMorning);
    lv_obj_set_width(ui_monitorBtn2, 240);
    lv_obj_set_height(ui_monitorBtn2, 60);
    lv_obj_set_x(ui_monitorBtn2, -20);
    lv_obj_set_y(ui_monitorBtn2, -20);
    lv_obj_set_align(ui_monitorBtn2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_monitorBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_monitorBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_monitorBtn2, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monitorBtn2, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_monitorBtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_monitorBtn2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monitorBtn2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMonitor2 = lv_label_create(ui_monitorBtn2);
    lv_obj_set_width(ui_labelMonitor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMonitor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelMonitor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMonitor2, "Monitor");
    lv_obj_set_style_text_font(ui_labelMonitor2, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_monitorBtn2, ui_event_monitorBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenMorning, ui_event_screenMorning, LV_EVENT_ALL, NULL);

}

void ui_screenMorning_screen_destroy(void)
{
    if(ui_screenMorning) lv_obj_del(ui_screenMorning);

    // NULL screen variables
    ui_screenMorning = NULL;
    ui_bgImg2 = NULL;
    ui_timeTempWidget2 = NULL;
    ui_Container3 = NULL;
    ui_labelHour2 = NULL;
    ui_lblTime2 = NULL;
    ui_labelTemp2 = NULL;
    ui_monitorBtn2 = NULL;
    ui_labelMonitor2 = NULL;

}
