// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENDAY_H
#define UI_SCREENDAY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenDay
extern void ui_screenDay_screen_init(void);
extern void ui_screenDay_screen_destroy(void);
extern void ui_event_screenDay(lv_event_t * e);
extern lv_obj_t * ui_screenDay;
extern lv_obj_t * ui_bgImg;
extern lv_obj_t * ui_timeTempWidget;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_labelHour;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_labelTemp;
extern void ui_event_monitorBtn(lv_event_t * e);
extern lv_obj_t * ui_monitorBtn;
extern lv_obj_t * ui_labelMonitor;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

