// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenSerial = NULL;
lv_obj_t * ui_topContainer = NULL;
lv_obj_t * ui_titleContainer = NULL;
lv_obj_t * ui_monitorTitle = NULL;
lv_obj_t * ui_btnContainer = NULL;
lv_obj_t * ui_pauseBtn = NULL;
lv_obj_t * ui_lblPauseBtn = NULL;
lv_obj_t * ui_recBtn = NULL;
lv_obj_t * ui_lblRecBtn = NULL;
lv_obj_t * ui_filterBtn = NULL;
lv_obj_t * ui_lblFilterBtn = NULL;
lv_obj_t * ui_clearBtn = NULL;
lv_obj_t * ui_lblClearBtn = NULL;
lv_obj_t * ui_usbBtn = NULL;
lv_obj_t * ui_lblUsbBtn = NULL;
lv_obj_t * ui_splitBtn = NULL;
lv_obj_t * ui_lblSplitBtn = NULL;
lv_obj_t * ui_dashBtn = NULL;
lv_obj_t * ui_lbldashBtn = NULL;
lv_obj_t * ui_stsBar = NULL;
lv_obj_t * ui_statusLineCount = NULL;
lv_obj_t * ui_separator1 = NULL;
lv_obj_t * ui_statusRecIndicator = NULL;
lv_obj_t * ui_separator2 = NULL;
lv_obj_t * ui_statusElapsed = NULL;
lv_obj_t * ui_terminalArea = NULL;
lv_obj_t * ui_terminalText = NULL;
// event funtions
void ui_event_dashBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

// build funtions

void ui_screenSerial_screen_init(void)
{
    ui_screenSerial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenSerial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenSerial, lv_color_hex(0x0D1636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenSerial, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topContainer = lv_obj_create(ui_screenSerial);
    lv_obj_remove_style_all(ui_topContainer);
    lv_obj_set_width(ui_topContainer, 800);
    lv_obj_set_height(ui_topContainer, 50);
    lv_obj_set_align(ui_topContainer, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_topContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_topContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_topContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_topContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topContainer, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titleContainer = lv_obj_create(ui_topContainer);
    lv_obj_remove_style_all(ui_titleContainer);
    lv_obj_set_width(ui_titleContainer, 195);
    lv_obj_set_height(ui_titleContainer, 50);
    lv_obj_set_align(ui_titleContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_titleContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_monitorTitle = lv_label_create(ui_titleContainer);
    lv_obj_set_width(ui_monitorTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_monitorTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_monitorTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_monitorTitle, "SENTINEL [COM3]");
    lv_obj_set_style_text_color(ui_monitorTitle, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_monitorTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_monitorTitle, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnContainer = lv_obj_create(ui_topContainer);
    lv_obj_remove_style_all(ui_btnContainer);
    lv_obj_set_width(ui_btnContainer, 537);
    lv_obj_set_height(ui_btnContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_btnContainer, 0);
    lv_obj_set_y(ui_btnContainer, 10);
    lv_obj_set_align(ui_btnContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_btnContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_btnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_btnContainer, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnContainer, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_pauseBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_pauseBtn, 50);
    lv_obj_set_height(ui_pauseBtn, 42);
    lv_obj_set_x(ui_pauseBtn, -286);
    lv_obj_set_y(ui_pauseBtn, 18);
    lv_obj_set_align(ui_pauseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pauseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pauseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pauseBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pauseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pauseBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pauseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pauseBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pauseBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pauseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_pauseBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pauseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPauseBtn = lv_label_create(ui_pauseBtn);
    lv_obj_set_width(ui_lblPauseBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPauseBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPauseBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPauseBtn, "||");

    ui_recBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_recBtn, 50);
    lv_obj_set_height(ui_recBtn, 42);
    lv_obj_set_x(ui_recBtn, -286);
    lv_obj_set_y(ui_recBtn, 18);
    lv_obj_set_align(ui_recBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_recBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_recBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_recBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_recBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_recBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_recBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_recBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_recBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_recBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_recBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_recBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRecBtn = lv_label_create(ui_recBtn);
    lv_obj_set_width(ui_lblRecBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRecBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblRecBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRecBtn, "REC");
    lv_obj_set_style_text_color(ui_lblRecBtn, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRecBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_filterBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_filterBtn, 50);
    lv_obj_set_height(ui_filterBtn, 42);
    lv_obj_set_x(ui_filterBtn, -286);
    lv_obj_set_y(ui_filterBtn, 18);
    lv_obj_set_align(ui_filterBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_filterBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_filterBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_filterBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_filterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_filterBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_filterBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_filterBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_filterBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_filterBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_filterBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_filterBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFilterBtn = lv_label_create(ui_filterBtn);
    lv_obj_set_width(ui_lblFilterBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFilterBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblFilterBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFilterBtn, "ALL");

    ui_clearBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_clearBtn, 50);
    lv_obj_set_height(ui_clearBtn, 42);
    lv_obj_set_x(ui_clearBtn, -286);
    lv_obj_set_y(ui_clearBtn, 18);
    lv_obj_set_align(ui_clearBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_clearBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_clearBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clearBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clearBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clearBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clearBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_clearBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_clearBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_clearBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_clearBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clearBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblClearBtn = lv_label_create(ui_clearBtn);
    lv_obj_set_width(ui_lblClearBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblClearBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblClearBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblClearBtn, "Clear");

    ui_usbBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_usbBtn, 50);
    lv_obj_set_height(ui_usbBtn, 42);
    lv_obj_set_x(ui_usbBtn, -286);
    lv_obj_set_y(ui_usbBtn, 18);
    lv_obj_set_align(ui_usbBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_usbBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_usbBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_usbBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_usbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_usbBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_usbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_usbBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_usbBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_usbBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_usbBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_usbBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblUsbBtn = lv_label_create(ui_usbBtn);
    lv_obj_set_width(ui_lblUsbBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblUsbBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblUsbBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblUsbBtn, "USB");

    ui_splitBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_splitBtn, 50);
    lv_obj_set_height(ui_splitBtn, 42);
    lv_obj_set_x(ui_splitBtn, -286);
    lv_obj_set_y(ui_splitBtn, 18);
    lv_obj_set_align(ui_splitBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_splitBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_splitBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_splitBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_splitBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_splitBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_splitBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_splitBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_splitBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_splitBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_splitBtn, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_splitBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSplitBtn = lv_label_create(ui_splitBtn);
    lv_obj_set_width(ui_lblSplitBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSplitBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSplitBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSplitBtn, "1x");

    ui_dashBtn = lv_btn_create(ui_btnContainer);
    lv_obj_set_width(ui_dashBtn, 117);
    lv_obj_set_height(ui_dashBtn, 42);
    lv_obj_set_x(ui_dashBtn, -286);
    lv_obj_set_y(ui_dashBtn, 18);
    lv_obj_set_align(ui_dashBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dashBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dashBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dashBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dashBtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dashBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dashBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_dashBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_dashBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbldashBtn = lv_label_create(ui_dashBtn);
    lv_obj_set_width(ui_lbldashBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbldashBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lbldashBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbldashBtn, "Dashboard");

    ui_stsBar = lv_obj_create(ui_screenSerial);
    lv_obj_remove_style_all(ui_stsBar);
    lv_obj_set_width(ui_stsBar, 800);
    lv_obj_set_height(ui_stsBar, 25);
    lv_obj_set_align(ui_stsBar, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_stsBar, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_stsBar, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_stsBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stsBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stsBar, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_stsBar, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_stsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_stsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_stsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusLineCount = lv_label_create(ui_stsBar);
    lv_obj_set_width(ui_statusLineCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusLineCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusLineCount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusLineCount, "0 lines");
    lv_obj_set_style_text_color(ui_statusLineCount, lv_color_hex(0xABAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusLineCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusLineCount, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator1 = lv_label_create(ui_stsBar);
    lv_obj_set_width(ui_separator1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_separator1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator1, "|");
    lv_obj_set_style_text_color(ui_separator1, lv_color_hex(0xABAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_separator1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_separator1, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusRecIndicator = lv_label_create(ui_stsBar);
    lv_obj_set_width(ui_statusRecIndicator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusRecIndicator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusRecIndicator, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusRecIndicator, "\n");
    lv_obj_set_style_text_color(ui_statusRecIndicator, lv_color_hex(0xABAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusRecIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusRecIndicator, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_separator2 = lv_label_create(ui_stsBar);
    lv_obj_set_width(ui_separator2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_separator2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_separator2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_separator2, "|");
    lv_obj_set_style_text_color(ui_separator2, lv_color_hex(0xABAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_separator2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_separator2, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statusElapsed = lv_label_create(ui_stsBar);
    lv_obj_set_width(ui_statusElapsed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_statusElapsed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_statusElapsed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_statusElapsed, "\n");
    lv_obj_set_style_text_color(ui_statusElapsed, lv_color_hex(0xABAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_statusElapsed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_statusElapsed, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_terminalArea = lv_obj_create(ui_screenSerial);
    lv_obj_remove_style_all(ui_terminalArea);
    lv_obj_set_width(ui_terminalArea, 736);
    lv_obj_set_height(ui_terminalArea, 370);
    lv_obj_set_x(ui_terminalArea, 0);
    lv_obj_set_y(ui_terminalArea, 20);
    lv_obj_set_align(ui_terminalArea, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_terminalArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_terminalArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_terminalArea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_terminalArea, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_terminalArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_terminalArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_terminalArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_terminalArea, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_terminalText = lv_label_create(ui_terminalArea);
    lv_obj_set_width(ui_terminalText, 700);
    lv_obj_set_height(ui_terminalText, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_terminalText, "> Daemon: ACTIVE\\\n> [COMPILER] Waiting...\\\n> Ready for stream.");
    lv_obj_set_style_text_color(ui_terminalText, lv_color_hex(0x00FFCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_terminalText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_terminalText, &ui_font_fontSmall, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_dashBtn, ui_event_dashBtn, LV_EVENT_ALL, NULL);

}

void ui_screenSerial_screen_destroy(void)
{
    if(ui_screenSerial) lv_obj_del(ui_screenSerial);

    // NULL screen variables
    ui_screenSerial = NULL;
    ui_topContainer = NULL;
    ui_titleContainer = NULL;
    ui_monitorTitle = NULL;
    ui_btnContainer = NULL;
    ui_pauseBtn = NULL;
    ui_lblPauseBtn = NULL;
    ui_recBtn = NULL;
    ui_lblRecBtn = NULL;
    ui_filterBtn = NULL;
    ui_lblFilterBtn = NULL;
    ui_clearBtn = NULL;
    ui_lblClearBtn = NULL;
    ui_usbBtn = NULL;
    ui_lblUsbBtn = NULL;
    ui_splitBtn = NULL;
    ui_lblSplitBtn = NULL;
    ui_dashBtn = NULL;
    ui_lbldashBtn = NULL;
    ui_stsBar = NULL;
    ui_statusLineCount = NULL;
    ui_separator1 = NULL;
    ui_statusRecIndicator = NULL;
    ui_separator2 = NULL;
    ui_statusElapsed = NULL;
    ui_terminalArea = NULL;
    ui_terminalText = NULL;

}
