// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#ifndef UI_SCREENSERIAL_H
#define UI_SCREENSERIAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screenSerial
extern void ui_screenSerial_screen_init(void);
extern void ui_screenSerial_screen_destroy(void);
extern lv_obj_t * ui_screenSerial;
extern lv_obj_t * ui_topContainer;
extern lv_obj_t * ui_titleContainer;
extern lv_obj_t * ui_monitorTitle;
extern lv_obj_t * ui_btnContainer;
extern lv_obj_t * ui_pauseBtn;
extern lv_obj_t * ui_lblPauseBtn;
extern lv_obj_t * ui_recBtn;
extern lv_obj_t * ui_lblRecBtn;
extern lv_obj_t * ui_filterBtn;
extern lv_obj_t * ui_lblFilterBtn;
extern lv_obj_t * ui_clearBtn;
extern lv_obj_t * ui_lblClearBtn;
extern lv_obj_t * ui_usbBtn;
extern lv_obj_t * ui_lblUsbBtn;
extern lv_obj_t * ui_splitBtn;
extern lv_obj_t * ui_lblSplitBtn;
extern void ui_event_dashBtn(lv_event_t * e);
extern lv_obj_t * ui_dashBtn;
extern lv_obj_t * ui_lbldashBtn;
extern lv_obj_t * ui_stsBar;
extern lv_obj_t * ui_statusLineCount;
extern lv_obj_t * ui_separator1;
extern lv_obj_t * ui_statusRecIndicator;
extern lv_obj_t * ui_separator2;
extern lv_obj_t * ui_statusElapsed;
extern lv_obj_t * ui_terminalArea;
extern lv_obj_t * ui_terminalText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

