// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenDay = NULL;
lv_obj_t * ui_bgImg = NULL;
lv_obj_t * ui_timeTempWidget = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_labelHour = NULL;
lv_obj_t * ui_lblTime = NULL;
lv_obj_t * ui_labelTemp = NULL;
lv_obj_t * ui_monitorBtn = NULL;
lv_obj_t * ui_labelMonitor = NULL;
// event funtions
void ui_event_screenDay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

void ui_event_monitorBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDashboard, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDashboard_screen_init);
    }
}

// build funtions

void ui_screenDay_screen_init(void)
{
    ui_screenDay = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenDay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bgImg = lv_img_create(ui_screenDay);
    lv_img_set_src(ui_bgImg, &ui_img_mty_dia_png);
    lv_obj_set_width(ui_bgImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bgImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bgImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bgImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bgImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeTempWidget = lv_obj_create(ui_screenDay);
    lv_obj_set_width(ui_timeTempWidget, 240);
    lv_obj_set_height(ui_timeTempWidget, 140);
    lv_obj_set_x(ui_timeTempWidget, -20);
    lv_obj_set_y(ui_timeTempWidget, -100);
    lv_obj_set_align(ui_timeTempWidget, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_flex_flow(ui_timeTempWidget, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_timeTempWidget, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timeTempWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_timeTempWidget, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_timeTempWidget, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_timeTempWidget, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_timeTempWidget, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_timeTempWidget);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelHour = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_labelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelHour, "1:00");
    lv_obj_set_style_text_color(ui_labelHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelHour, &ui_font_fontBig, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_lblTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "PM");
    lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelTemp = lv_label_create(ui_timeTempWidget);
    lv_obj_set_width(ui_labelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTemp, "32°C Monterrey, NL");
    lv_obj_set_style_text_color(ui_labelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelTemp, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelTemp, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_monitorBtn = lv_btn_create(ui_screenDay);
    lv_obj_set_width(ui_monitorBtn, 240);
    lv_obj_set_height(ui_monitorBtn, 60);
    lv_obj_set_x(ui_monitorBtn, -20);
    lv_obj_set_y(ui_monitorBtn, -20);
    lv_obj_set_align(ui_monitorBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_monitorBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_monitorBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_monitorBtn, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_monitorBtn, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_monitorBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_monitorBtn, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_monitorBtn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelMonitor = lv_label_create(ui_monitorBtn);
    lv_obj_set_width(ui_labelMonitor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelMonitor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_labelMonitor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelMonitor, "Monitor");
    lv_obj_set_style_text_font(ui_labelMonitor, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_monitorBtn, ui_event_monitorBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screenDay, ui_event_screenDay, LV_EVENT_ALL, NULL);

}

void ui_screenDay_screen_destroy(void)
{
    if(ui_screenDay) lv_obj_del(ui_screenDay);

    // NULL screen variables
    ui_screenDay = NULL;
    ui_bgImg = NULL;
    ui_timeTempWidget = NULL;
    ui_Container1 = NULL;
    ui_labelHour = NULL;
    ui_lblTime = NULL;
    ui_labelTemp = NULL;
    ui_monitorBtn = NULL;
    ui_labelMonitor = NULL;

}
