// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Monitor

#include "ui.h"

lv_obj_t * ui_screenDashboard = NULL;
lv_obj_t * ui_comContainer = NULL;
lv_obj_t * ui_lblTitleDash = NULL;
lv_obj_t * ui_hubBtn = NULL;
lv_obj_t * ui_lblBtn = NULL;
lv_obj_t * ui_btConnectionSts = NULL;
lv_obj_t * ui_btLbl = NULL;
lv_obj_t * ui_btSts = NULL;
// event funtions
void ui_event_hubBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDay_screen_init);
    }
}

void ui_event_btConnectionSts(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_screenDay, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_screenDay_screen_init);
    }
}

// build funtions

void ui_screenDashboard_screen_init(void)
{
    ui_screenDashboard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screenDashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screenDashboard, lv_color_hex(0x0D1636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screenDashboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_comContainer = lv_obj_create(ui_screenDashboard);
    lv_obj_set_width(ui_comContainer, 700);
    lv_obj_set_height(ui_comContainer, 350);
    lv_obj_set_x(ui_comContainer, 0);
    lv_obj_set_y(ui_comContainer, -20);
    lv_obj_set_align(ui_comContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_comContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_comContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_comContainer, lv_color_hex(0x535353), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_comContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_comContainer, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTitleDash = lv_label_create(ui_screenDashboard);
    lv_obj_set_width(ui_lblTitleDash, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTitleDash, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTitleDash, 0);
    lv_obj_set_y(ui_lblTitleDash, 30);
    lv_obj_set_align(ui_lblTitleDash, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTitleDash, "Seleccionar COM");
    lv_obj_set_style_text_color(ui_lblTitleDash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTitleDash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTitleDash, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hubBtn = lv_btn_create(ui_screenDashboard);
    lv_obj_set_width(ui_hubBtn, 100);
    lv_obj_set_height(ui_hubBtn, 50);
    lv_obj_set_x(ui_hubBtn, 50);
    lv_obj_set_y(ui_hubBtn, 30);
    lv_obj_add_flag(ui_hubBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_hubBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_hubBtn, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hubBtn, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBtn = lv_label_create(ui_hubBtn);
    lv_obj_set_width(ui_lblBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBtn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblBtn, "HUB");

    ui_btConnectionSts = lv_btn_create(ui_screenDashboard);
    lv_obj_set_width(ui_btConnectionSts, 150);
    lv_obj_set_height(ui_btConnectionSts, 50);
    lv_obj_set_x(ui_btConnectionSts, -50);
    lv_obj_set_y(ui_btConnectionSts, 30);
    lv_obj_set_align(ui_btConnectionSts, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_btConnectionSts, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btConnectionSts, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btConnectionSts, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btConnectionSts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btConnectionSts, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btConnectionSts, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btConnectionSts, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btConnectionSts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btLbl = lv_label_create(ui_btConnectionSts);
    lv_obj_set_width(ui_btLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btLbl, "Sin Conexión   ");
    lv_obj_set_style_text_font(ui_btLbl, &ui_font_fontMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btSts = lv_obj_create(ui_btConnectionSts);
    lv_obj_set_width(ui_btSts, 10);
    lv_obj_set_height(ui_btSts, 10);
    lv_obj_set_align(ui_btSts, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btSts, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btSts, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btSts, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btSts, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btSts, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_hubBtn, ui_event_hubBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btConnectionSts, ui_event_btConnectionSts, LV_EVENT_ALL, NULL);

}

void ui_screenDashboard_screen_destroy(void)
{
    if(ui_screenDashboard) lv_obj_del(ui_screenDashboard);

    // NULL screen variables
    ui_screenDashboard = NULL;
    ui_comContainer = NULL;
    ui_lblTitleDash = NULL;
    ui_hubBtn = NULL;
    ui_lblBtn = NULL;
    ui_btConnectionSts = NULL;
    ui_btLbl = NULL;
    ui_btSts = NULL;

}
