[env:esp32-c3-devkitm-1]
platform = espressif32 @ 6.6.0
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    h2zero/NimBLE-Arduino @ 1.4.1 ; Version compatible estable
    lemmingdev/ESP32-BLE-Gamepad @ 0.5.2
